### PR TITLE
TaskScheduler tweaks

### LINKED ISSUE #49: There is an issue causing program to crash on start due to startup handling
This code in OpenHardwareMonitor/GUI/StartupManager.cs: 
```c#
    private void DeleteSchedulerTask() {
      ITaskFolder root = scheduler.GetFolder("\\");
      try {
        ITaskFolder folder = root.GetFolder("Open Hardware Monitor");
        folder.DeleteTask("Startup", 0);
      } catch (IOException) { }
      try {
        root.DeleteFolder("Open Hardware Monitor", 0);
      } catch (IOException) { }
    }
```
implies there is a "Startup" task, tries to remove it and then tries to remove the folder aswell. 

However, if there are any other startup tasks in the folder, it will fail to delete the folder, will crash the app with an error error:

```
Application: OpenHardwareMonitor.exe
CoreCLR Version: 6.0.2023.32017
.NET Version: 6.0.20
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80070091): Папка не пуста. (0x80070091)
   at OpenHardwareMonitor.TaskScheduler.ITaskFolder.DeleteFolder(String subFolderName, Int32 flags)
   at OpenHardwareMonitor.GUI.StartupManager.DeleteSchedulerTask() in C:\projects\openhardwaremonitor\OpenHardwareMonitor\GUI\StartupManager.cs:line 232
   at OpenHardwareMonitor.GUI.StartupManager.ConfigureAutoStartup(Boolean enable, Boolean atBootup) in C:\projects\openhardwaremonitor\OpenHardwareMonitor\GUI\StartupManager.cs:line 291
   at OpenHardwareMonitor.GUI.MainForm.<.ctor>b__42_9(Object sender, EventArgs e) in C:\projects\openhardwaremonitor\OpenHardwareMonitor\GUI\MainForm.cs:line 284
   at OpenHardwareMonitor.GUI.UserOption.add_Changed(EventHandler value) in C:\projects\openhardwaremonitor\OpenHardwareMonitor\GUI\UserOption.cs:line 98
   at OpenHardwareMonitor.GUI.MainForm..ctor() in C:\projects\openhardwaremonitor\OpenHardwareMonitor\GUI\MainForm.cs:line 278
   at OpenHardwareMonitor.Program.Main(String[] args) in C:\projects\openhardwaremonitor\OpenHardwareMonitor\Program.cs:line 52
```
The exception, however, isn't handled, as you can see, as it's COMException.
"Папка не пуста" == Folder is not empty.

This happened to me on the first launch of the app, since I've run custom tasks with an official version prior to installation of this one.

I'd also suggest to avoid even trying to delete this task scheduler folder, since user may try to put their own scripts here, and deleting them would be wrong.

### PR DESCRIPTION
**Pull request by easymoney322**
Fixes #49

### CODE REVIEW

File: OpenHardwareMonitor/GUI/StartupManager.cs [hunk 1]
```diff
@@ -238,11 +234,23 @@ private void DeleteSchedulerTask()
             try
             {
                 // Previous versions might have registered under this name
-                root.DeleteTask("OpenHardwareMonitorAutoStart", 0);
+                root.DeleteTask("OpenHardwareMonitorAutoStart", 0); 
             }
             catch (IOException)
             {
             }
+
```
Comment (pgrawehr) [inline OpenHardwareMonitor/GUI/StartupManager.cs:242]: Thanks for cleaning this up. While it's not a new problem, these "catch and ignore" handlers are very ugly. Can you add exception logging for the error cases, so that the log file contains information when any of this fails? You can get a logger by calling `Logging.GetLogger("some name")`.

Comment (easymoney322) [reply OpenHardwareMonitor/GUI/StartupManager.cs:247]: I didn't like that exception handling either, but I opted not to change it.

I've tried to implement logger support the same way as [Hardware/HDD/WindowsSmart.cs](https://github.com/hexagon-oss/openhardwaremonitor/blob/c60ac4bd1af591f8332ea035b2584ce46d66ce76/OpenHardwareMonitorLib/Hardware/HDD/WindowsSmart.cs#L225) in my commit 6231c0dcc8092ac34a6b9245a39402ed9e3b35a7 .

Please note, that I didn't wrote a single line of C#/.NET 6 code before these commits, and I have zero clue about how this logger library works. 
However, I wasn't able to crash the app by adding\removing tasks, closing on re-opening app, even after by setting ` taskCount = -5 ` to bypass the check. And there is an output in VStudio output window about these errors:
```
2023-08-15 04:45:29.9545|638276895299545874|1|Error|OpenHardwareMonitor.GUI.StartupManager: Папка не пуста. (0x80070091) Папка не пуста. (0x80070091)
2023-08-15 04:45:29.9545|638276895299545874|1|Error|OpenHardwareMonitor.GUI.StartupManager: Не удается найти указанный файл. (0x80070002) Не удается найти указанный файл. (0x80070002)
```
(Folder isn't empty and the file not found, respectively). I ain't sure if there was an output before, tho.

Comment (pgrawehr) [reply OpenHardwareMonitor/GUI/StartupManager.cs:247]: Hey, that's very good for someone new to the .NET world. It's really almost perfect now, except that you should move the `this.GetCurrentClassLogger()` line to the constructor of the class, not repeat it in every exception.

**Comment by easymoney322** [comment]
I've moved it to class constructor, please review the code

File: OpenHardwareMonitor/GUI/StartupManager.cs (hunk 1 above)
Comment (easymoney322) [reply OpenHardwareMonitor/GUI/StartupManager.cs:247]: I've moved it to class constructor, please review the code

File: OpenHardwareMonitor/GUI/StartupManager.cs [hunk 2]
```diff
@@ -217,31 +221,40 @@ private bool CreateSchedulerTask(bool atBootup)
...
             }
 
-            try
-            {
-                // Previous versions might have registered under this name
-                root.DeleteTask("OpenHardwareMonitorAutoStart", 0);
-            }
-            catch (IOException)
-            {
+            if (0 < taskCount)
```
Comment (pgrawehr) [inline OpenHardwareMonitor/GUI/StartupManager.cs:248]: Shouldn't this be `if (0 == taskCount)`? This deletes the folder whenever taskCount is > 0

Comment (easymoney322) [reply OpenHardwareMonitor/GUI/StartupManager.cs:248]: > Shouldn't this be `if (0 == taskCount)`? This deletes the folder whenever taskCount is > 0

Yes, you are right. It should be 0==taskCount.
I wonder if checking for task count even makes sense, other than reducing the amount of exceptions raised, since we try to delete folder in a try\catch block anyway. Maybe its pointless overcomplication.

Task updating block may not occur if the folder does not contain "Startup" task, leaving it to "-1". If the folder is also empty, since the condition wouldnt be met, the folder won't get deleted.

I'm unaware of try\catch overhead in C#, but I'd suggest two options:
1. The only thing we change, compared to the release version, is add one other type to exception handling+add logging. So we dont check task count, since we do everything in try\catch blocks anyway.
2. We add local bool variable, check if patch exists in try\catch block, update the bool variable if it is, and do braching based on said variable: trying to delete "Startup" task and\or folder only may occur if the folder itself exists. It may make code harder to read. It also may speed up the code, if try\catch blocks and/or Win32 API overhead is a thing.

Comment (pgrawehr) [reply OpenHardwareMonitor/GUI/StartupManager.cs:248]: Try/catch blocks have some overhead (or rather, handling the exception has), but since this code runs only once and not in a loop, that is negligible. You can go with solution 1.

Comment (easymoney322) [reply OpenHardwareMonitor/GUI/StartupManager.cs]: I did as you suggested.

**Review by pgrawehr — APPROVED** [review]
